HealthierJob Site/HealthierJob/HealthierJob/Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Mvc;

namespace HealthierJob.Controllers
{
    public class FeedbackController : Controller
    {
        
        MetodosController metodos = new MetodosController();

        public IActionResult Retornar()
        {

			if (metodos.VerificaLogado(HttpContext) == true)
			{

                Usuario u = metodos.RetornaObjeto(HttpContext);

                string s = DateTime.Now.ToShortDateString();
                DateTime.TryParse(s, out var data);

                Feedback f = new Feedback(u.Codigo, 0, 0, 0, data, 0, "");

                if (f.RetornaFeedback() != null)
                {
                    ViewData["f"] = f.RetornaFeedback();

                    return View();
                } else
                {
                    TempData["msg"] = "Responda o Questionário para Obter o Feedback";
                    return RedirectToAction("Responder", "Questionario");
                }
			}
			else
			{
                TempData["msg"] = "Logue antes de continuar";
				return RedirectToAction("Login", "Usuario");
			}
			
        }

        public IActionResult Calendario()
        {

            if(metodos.VerificaLogado(HttpContext) == true)
            {
				if (TempData["data"] != null)
				{
					Usuario u = metodos.RetornaObjeto(HttpContext);

                    string s = TempData["data"].ToString();
                    DateTime.TryParse(s, out var data);

                    Feedback f = new Feedback(u.Codigo, 0, 0, 0, data, 0, "");

					if(f.RetornaFeedback() != null)
                    {
                        ViewData["f"] = f.RetornaFeedback();
                    } else
                    {
                        ViewData["f"] = "vazio";
                    }
				}

				return View();
			} else
            {
				TempData["msg"] = "Logue antes de continuar";
				return RedirectToAction("Login", "Usuario");
            }
        }

        [HttpPost]
        public IActionResult Calendario(DateTime data)
        {

            TempData["data"] = data;

            return RedirectToAction("Calendario");
        }
    }
}

HealthierJob Site/HealthierJob/HealthierJob/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace HealthierJob
{
    public class UsuarioController : Controller
    {
        MetodosController metodos = new MetodosController();

        public IActionResult Cadastrar()
        {
            if (metodos.VerificaLogado(this.HttpContext) == true)
            {
                if (metodos.VerificaAdm(this.HttpContext) == true)
                {

                    if (TempData["msg"] != null)
                    {
                        TempData.Clear(); 
                    } 

                    return View();
                }
                else
                {
                    return RedirectToAction("Inicial", "Home");
                }

            }
            else
            {
                TempData["msg"] = "Logue antes de continuar";
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        public IActionResult Cadastrar(string tipo, string status, string codigo, string nomeCompleto, int idade, string areaAtuacao,
            DateTime dataEntrada, DateTime dataSaida, string senha)
        {

            byte[] img = null;

            try
            {
                foreach (IFormFile arquivo in Request.Form.Files)
                {
                    string tipoArquivo = arquivo.ContentType;

                    if (tipoArquivo.Contains("png") || tipoArquivo.Contains("jpg") || tipoArquivo.Contains("jpeg"))
                    {
                        MemoryStream s = new MemoryStream();
                        arquivo.CopyToAsync(s);
                        byte[] bytesArquivo = s.ToArray();

                        img = bytesArquivo;
                    }
                    else
                    {
                        TempData["msg"] = "Favor Inserir um Tipo de Imagem Válida";
                        return View();
                    }
                }
            } catch (Exception e)
            {
                TempData["msg"] = "Tamanho da Imagem Muito Grande";
                return View();
            }

            Usuario u = new Usuario(metodos.RemoveEspaco(tipo), metodos.RemoveEspaco(status), metodos.RemoveEspaco(codigo), metodos.RemoveEspaco(nomeCompleto),
                idade, metodos.RemoveEspaco(areaAtuacao), dataEntrada, dataSaida, metodos.RemoveEspaco(senha), img);

            TempData["msg"] = u.Cadastrar();

            if (TempData["msg"].ToString().Contains("Sucesso"))
            {
                return RedirectToAction("Cadastrar");

            } else
            {
                return View();
            }
        }

        public IActionResult Login()
        {
            if (metodos.VerificaLogado(this.HttpContext) == false)
            {
                return View();
            }
            else
            {
                TempData["msg"] = "Você já está logado";
                return RedirectToAction("Inicial", "Home");
            }
        }

        [HttpPost]
        public IActionResult Login(string codigo, string senha)
        {

            DateTime data = DateTime.ParseExact("11/11/1111", "dd/MM/yyyy", null);

            Usuario u = new Usuario("", "", codigo, "", 0, "", data, data, senha, null);

            Usuario user = u.Verificar();

            if (user != null)
            {

                HttpContext.Session.SetString("user", JsonConvert.SerializeObject(user));

                return RedirectToAction("Inicial", "Home");

            }
            else
            {
                TempData["msg"] = "Usuário ou Senha Incorretos";
                return RedirectToAction("Login");
            }

        }

        public IActionResult Editar(string id)
        {
            if (metodos.VerificaLogado(this.HttpContext) == true)
            {
                if (metodos.VerificaAdm(this.HttpContext) == true)
                {

                    Usuario sessao = metodos.RetornaObjeto(HttpContext);

                    if (id == sessao.Codigo)
                    {

                        ViewData["u"] = sessao;
                        return View();

                    }
                    else
                    {

                        DateTime data = DateTime.ParseExact("11/11/1111", "dd/MM/yyyy", null);

                        Usuario u = new Usuario("", "", id, "", 0, "", data, data, "", null);

                        if (u.RetornarUsu() != null)
                        {
                            ViewData["u"] = u.RetornarUsu();
                            return View();

                        }
                        else
                        {
                            TempData["msg"] = "Não foi Possível Executar essa Ação";
                            return RedirectToAction("Listar");
                        }

                    }
                }
                else
                {
                    return RedirectToAction("Inicial", "Home");
                }
            }
            else
            {
                TempData["msg"] = "Logue Antes de Continuar";
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        public IActionResult Editar(string tipo, string status, string codigo, string nomeCompleto, int idade, string areaAtuacao,
            DateTime dataEntrada, DateTime dataSaida, string senha)
        {
            byte[] img = null;

            try
            {
                foreach (IFormFile arquivo in Request.Form.Files)
                {
                    string tipoArquivo = arquivo.ContentType;

                    if (tipoArquivo.Contains("png") || tipoArquivo.Contains("jpg") || tipoArquivo.Contains("jpeg"))
                    {
                        MemoryStream s = new MemoryStream();
                        arquivo.CopyToAsync(s);
                        byte[] bytesArquivo = s.ToArray();

                        img = bytesArquivo;
                    }
                    else
                    {
                        TempData["msg"] = "Favor Inserir um Tipo de Imagem Válida";
                        return View();
                    }
                }
            }
            catch (Exception e)
            {
                TempData["msg"] = "Tamanho da Imagem Muito Grande";
                return View();
            }

            if (senha != null)
            {
                senha = metodos.RemoveEspaco(senha);
            } 

            Usuario u = new Usuario(metodos.RemoveEspaco(tipo), metodos.RemoveEspaco(status), codigo, metodos.RemoveEspaco(nomeCompleto),
                idade, metodos.RemoveEspaco(areaAtuacao), dataEntrada, dataSaida, senha, img);

            Usuario user = metodos.RetornaObjeto(HttpContext);

            TempData["msg"] = u.Editar();

            if (user.Codigo == codigo)
            {
                HttpContext.Session.SetString("user", JsonConvert.SerializeObject(u));
            }

            return RedirectToAction("Listar");
        }

        public IActionResult Listar()
        {
            if (metodos.VerificaLogado(this.HttpContext) == true)
            {
                if (metodos.VerificaAdm(this.HttpContext) == true)
                {
                    return View(Usuario.Listar());
                }
                else
                {
                    return RedirectToAction("Inicial", "Home");
                }
            }
            else
            {
                TempData["msg"] = "Logue antes de Continuar";
                return RedirectToAction("Login");
            }
        }

        public IActionResult Sair()
        {
            HttpContext.Session.Remove("user");

            TempData.Clear();

            return RedirectToAction("Login");
        }

        public IActionResult InativarAtivar(string acao, string id)
        {
            DateTime data = DateTime.ParseExact("11/11/1111", "dd/MM/yyyy", null);

            Usuario u = new Usuario("", acao, id, "", 0, "", data, data, "", null);

            TempData["msg"] = u.InativarAtivar();

            return RedirectToAction("Listar");
        }
    }
}

HealthierJob Site/HealthierJob/HealthierJob/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

@{
    MetodosController metodos = new MetodosController();
}

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="~/css/navfooter.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HealthierJob.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.quicksearch/2.3.1/jquery.quicksearch.js"></script>
    
    <link rel="icon" href="IMG/HealthierJob+-removebg-preview.png">
</head>

<body>
    <partial name="_Toast" />

    <header>
        @{
            if(metodos.VerificaLogado(this.Context) == true)
            {
                Usuario u = metodos.RetornaObjeto(this.Context);

                <nav>
                    <a class="logo" asp-controller="Home" asp-action="Inicial">HealthierJob+</a>
                    <ul class="nav-list">
                        <li><a asp-controller="Home" asp-action="Faq">FAQ</a></li>
                        <li><a asp-controller="Questionario" asp-action="Responder">RESPONDER QUESTIONÁRIO</a></li>
                        <li><a asp-controller="Feedback" asp-action="Retornar">FEEDBACK DIÁRIO</a></li>
                        <li><a asp-controller="Feedback" asp-action="Calendario">PESQUISAR FEEDBACK</a></li>
                        <li><a asp-controller="Usuario" asp-action="Sair">SAIR</a></li>
                    </ul>
                </nav>
            }
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <script>
        config = { dateFormat: "Y-m-d", altInput: true, altFormat: "d/m/Y", }
        config2 = { enableTime: true, noCalendar: true, dateFormat: "H:i", time_24hr: true }

        flatpickr("#data", config);
        flatpickr("#time", config2);

        $('input#txt_consulta').quicksearch('table#tabela tbody tr');
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HealthierJob Site/HealthierJob/HealthierJob/Views/Shared/_Toast.cshtml
@if(TempData["msg"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">

        toastr.options.closeButton = false;

        if (@TempData["msg"].ToString().ToLower().IndexOf("sucesso") > 0) 
        {
            toastr.success('@TempData["msg"]');
        }
        else
        {
            toastr.error('@TempData["msg"]');
        }
    </script>    
}